using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;

namespace clibridge4unity;

/// <summary>
/// Discovers + loads Roslyn source generators that Unity recognizes via the `RoslynAnalyzer`
/// asset label. Catches generator-emitted types (Burst, Mirror, Photon Fusion, MessagePack-CSharp,
/// etc.) so LINT unity doesn't false-positive on `<auto-generated>` types.
///
/// Discovery: walk every `.dll.meta` in Assets/ + Library/PackageCache/, parse YAML for
/// `labels:` containing `RoslynAnalyzer`. Sibling `.dll` is the analyzer/generator assembly.
/// Loaded via reflection — failures are silent (generator may target a different Roslyn version).
/// Cached per process so the discovery scan runs once per daemon lifetime.
/// </summary>
internal static class LintSourceGenerators
{
    sealed class Cache
    {
        public string ProjectPath;
        public List<ISourceGenerator> Generators;
        public List<DiagnosticAnalyzer> Analyzers;
        public List<string> LoadFailures;
    }

    static Cache _cache;
    static readonly object _lock = new();

    /// <summary>Returns (generators, loadFailures) for `projectPath`. Cached after first call.</summary>
    public static (List<ISourceGenerator> generators, List<string> failures) Discover(string projectPath)
    {
        lock (_lock)
        {
            if (_cache != null && _cache.ProjectPath == projectPath)
                return (_cache.Generators, _cache.LoadFailures);

            var result = new Cache { ProjectPath = projectPath, Generators = new(), Analyzers = new(), LoadFailures = new() };
            var seenDll = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            string[] roots = { Path.Combine(projectPath, "Assets"), Path.Combine(projectPath, "Packages"),
                               Path.Combine(projectPath, "Library", "PackageCache") };

            foreach (var root in roots)
            {
                if (!Directory.Exists(root)) continue;
                IEnumerable<string> metaFiles;
                try { metaFiles = Directory.EnumerateFiles(root, "*.dll.meta", SearchOption.AllDirectories); }
                catch { continue; }
                foreach (var meta in metaFiles)
                {
                    if (!IsRoslynAnalyzerLabeled(meta)) continue;
                    string dll = meta.Substring(0, meta.Length - ".meta".Length);
                    if (!File.Exists(dll)) continue;
                    if (!seenDll.Add(dll)) continue;
                    LoadGeneratorAssembly(dll, result);
                }
            }
            _cache = result;
            return (result.Generators, result.LoadFailures);
        }
    }

    /// <summary>Cheap YAML scan: a `.dll.meta` is treated as an analyzer if its labels list
    /// contains the literal string `RoslynAnalyzer`.</summary>
    static bool IsRoslynAnalyzerLabeled(string metaPath)
    {
        try
        {
            string text = File.ReadAllText(metaPath);
            int idx = text.IndexOf("RoslynAnalyzer", StringComparison.Ordinal);
            return idx >= 0;
        }
        catch { return false; }
    }

    static void LoadGeneratorAssembly(string dllPath, Cache result)
    {
        try
        {
            // ReflectionOnlyLoadFrom would be safer but generators need real exec.
            var asm = Assembly.LoadFrom(dllPath);
            Type[] types;
            try { types = asm.GetTypes(); }
            catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t != null).ToArray(); }
            foreach (var t in types)
            {
                if (t == null || t.IsAbstract || !t.IsClass) continue;
                // Source generator: ISourceGenerator (legacy) or IIncrementalGenerator (modern).
                bool isLegacyGen = ImplementsInterface(t, "Microsoft.CodeAnalysis.ISourceGenerator");
                bool isIncrementalGen = ImplementsInterface(t, "Microsoft.CodeAnalysis.IIncrementalGenerator");
                if (isLegacyGen || isIncrementalGen)
                {
                    try
                    {
                        var instance = Activator.CreateInstance(t);
                        // Wrap incremental generator into ISourceGenerator via Roslyn's adapter
                        // (so we can pass everything as ISourceGenerator into the driver).
                        if (instance is ISourceGenerator sg) result.Generators.Add(sg);
                        else if (isIncrementalGen)
                        {
                            // GeneratorExtensions.AsSourceGenerator extension wraps it.
                            var asSg = typeof(GeneratorExtensions).GetMethod("AsSourceGenerator");
                            if (asSg != null)
                            {
                                var wrapped = asSg.Invoke(null, new[] { instance });
                                if (wrapped is ISourceGenerator wrappedSg) result.Generators.Add(wrappedSg);
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        result.LoadFailures.Add($"{Path.GetFileName(dllPath)}:{t.Name} — {ex.GetType().Name}: {ex.Message}");
                    }
                }
                // Also pick up DiagnosticAnalyzer subclasses for completeness (not used by compile but recorded).
                else if (typeof(DiagnosticAnalyzer).IsAssignableFrom(t))
                {
                    try { if (Activator.CreateInstance(t) is DiagnosticAnalyzer da) result.Analyzers.Add(da); }
                    catch { }
                }
            }
        }
        catch (Exception ex)
        {
            result.LoadFailures.Add($"{Path.GetFileName(dllPath)} — {ex.GetType().Name}: {ex.Message}");
        }
    }

    static bool ImplementsInterface(Type t, string fullName)
    {
        foreach (var i in t.GetInterfaces())
            if (i.FullName == fullName) return true;
        return false;
    }

    /// <summary>Run all discovered source generators against `compilation`. Returns the new
    /// compilation containing generated trees, or the original if no generators apply.
    /// Cancellation is forwarded into the generator driver so a runaway generator can be killed.</summary>
    public static CSharpCompilation RunGenerators(CSharpCompilation compilation, IReadOnlyList<ISourceGenerator> generators, CSharpParseOptions parseOpts, CancellationToken ct = default)
    {
        if (generators == null || generators.Count == 0) return compilation;
        try
        {
            var driver = CSharpGeneratorDriver.Create(generators, parseOptions: parseOpts);
            driver = (CSharpGeneratorDriver)driver.RunGeneratorsAndUpdateCompilation(compilation, out var updated, out _, ct);
            return (CSharpCompilation)updated;
        }
        catch (OperationCanceledException) { throw; }
        catch
        {
            return compilation;
        }
    }
}
